Repository wvlet/wvlet, pull requests merged in 2024-10, with the labels that each got.

#271 internal: Add a step for homebrew PR creation
  .github/workflows/release.yml
Labels: internal

#272 internal: Create a PR for Homebrew upon release
  .github/workflows/release.yml
Labels: internal

#273 internal: Remove unnecessary release workflow condition
  .github/workflows/release.yml
Labels: internal

#275 lang (feature): Allow saving debug path results
  spec/basic/debug-save.wv
  website/docs/internal/grammar.md
  wvlet-lang/src/main/scala/wvlet/lang/compiler/analyzer/SymbolLabeler.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/parser/WvletParser.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/planner/ExecutionPlanner.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/LogicalPlanPrinter.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/execution.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/relation.scala
Labels: feature, doc

#277 lang (feature): rename (column) as (alias)
  spec/basic/rename.wv
  website/docs/syntax/relational-operators.md
  wvlet-lang/src/main/scala/wvlet/lang/compiler/Name.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/codegen/GenSQL.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/parser/WvletParser.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/parser/WvletToken.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/DataType.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/relation.scala
Labels: feature, doc

#278 lang (internal #182): Option[NodeLocation] -> NodeLocation
  wvlet-lang/src/main/scala/wvlet/lang/StatusCode.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/CompilationUnit.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/SourceLocation.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/codegen/GenSQL.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/parser/WvletScanner.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/transform/TrinoRewritePivot.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/NodeLocation.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/TreeNode.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/expr/Attribute.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/expr/Expression.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/expr/ResolvedAttribute.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/expr/exprs.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/LogicalPlan.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/ddl.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/plan.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/relation.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/update.scala
Labels: internal

#279 lang (internal #182): Replace NodeLocation to Span in TreeNode
  wvlet-lang/src/main/scala/wvlet/lang/StatusCode.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/Compiler.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/SourceFile.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/analyzer/TypeResolver.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/codegen/GenSQL.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/parser/Span.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/parser/WvletParser.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/parser/WvletScanner.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/transform/Incrementalize.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/transform/PreprocessLocalExprs.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/transform/RewriteExpr.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/transform/TrinoRewritePivot.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/NodeLocation.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/TreeNode.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/expr/Attribute.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/expr/Expression.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/expr/ResolvedAttribute.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/expr/exprs.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/LogicalPlan.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/LogicalPlanPrinter.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/ddl.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/plan.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/relation.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/update.scala
  wvlet-lang/src/test/scala/wvlet/lang/compiler/analyzer/CDPBehaviorTest.scala
Labels: internal

#284 lang (fix): Ignore .wv files in target folders
  wvlet-lang/src/main/scala/wvlet/lang/compiler/CompilationUnit.scala
Labels: bug

#285 doc: Use execute for TPC-H gen
  website/docs/syntax/quick-start.md
Labels: doc

#286 lang (feature): Support casting null
  spec/basic/null-cast.wv
  wvlet-lang/src/main/scala/wvlet/lang/compiler/analyzer/TypeResolver.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/parser/WvletParser.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/parser/WvletToken.scala
  wvlet-stdlib/module/standard/null.wv
Labels: feature

#288 lang (feature): val definition support. closes #250"
  spec/basic/val.wv
  website/docs/syntax/expressions.md
  wvlet-lang/src/main/scala/wvlet/lang/compiler/Symbolnfo.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/analyzer/SymbolLabeler.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/analyzer/TypeResolver.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/codegen/GenSQL.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/parser/WvletParser.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/parser/WvletToken.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/planner/ExecutionPlanner.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/transform/ExpressionEvaluator.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/transform/RewriteExpr.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/expr/exprs.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/LogicalPlanPrinter.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/execution.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/plan.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/relation.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/QueryExecutor.scala
Labels: feature, doc

#289 lang (fix): describe should handle empty schema
  spec/basic/describe.wv
  wvlet-lang/src/main/scala/wvlet/lang/compiler/DBType.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/codegen/GenSQL.scala
Labels: bug

#290 lang (internal #283): Add SourceFile.lastUpdatedAt
  wvlet-lang/src/main/scala/wvlet/lang/compiler/Context.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/SourceFile.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/VirtualFile.scala
Labels: internal

#291 lang (feature): Reload modified .wv files. Resolves #283
  wvlet-lang/src/main/scala/wvlet/lang/compiler/CompilationUnit.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/Compiler.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/SourceFile.scala
Labels: feature

#292 lang (internal): Load SourceFile lazily
  wvlet-lang/src/main/scala/wvlet/lang/compiler/CompilationUnit.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/SourceFile.scala
Labels: internal

#293 lang (internal): Load source content/line index lazily
  wvlet-lang/src/main/scala/wvlet/lang/compiler/CompilationUnit.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/SourceFile.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/parser/ParserPhase.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/parser/WvletScanner.scala
  wvlet-lang/src/test/scala/wvlet/lang/compiler/SourceFileTest.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/cli/WvletREPL.scala
Labels: internal

#294 lang (feature #87): Add a header comment to generated SQL
  wvlet-lang/src/main/scala/wvlet/lang/compiler/SourceFile.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/VirtualFile.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/codegen/GenSQL.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/QueryExecutor.scala
Labels: feature

#299 editor (feature): Add Web UI template
  wvlet-ui-main/index.css
  wvlet-ui-main/index.html
  wvlet-ui-main/main.js
  wvlet-ui-main/package-lock.json
  wvlet-ui-main/package.json
  wvlet-ui-main/postcss.config.js
  wvlet-ui-main/public/img/apple-touch-icon.png
  wvlet-ui-main/public/img/favicon-16x16.png
  wvlet-ui-main/public/img/favicon-32x32.png
  wvlet-ui-main/public/img/favicon.ico
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/WvletUIMain.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/ConsoleLogWindow.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/PreviewWindow.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletEditor.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletMonacoEditor.scala
  wvlet-ui-main/tailwind.config.js
  wvlet-ui/src/main/scala/wvlet/lang/ui/component/MainFrame.scala
  wvlet-ui/src/test/scala/wvlet/lang/ui/component/MainFrameTest.scala
Labels: feature

#300 editor (feature): Add Monaco editor to UI
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletMonacoEditor.scala
Labels: feature

#301 internal: Fix module name
  package-lock.json
Labels: bug, internal

#303 editor (feature): Add monaco highlight
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletMonacoEditor.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletMonarchLanguage.scala
Labels: feature

#302 editor (feature): Add RPC interface
  build.sbt
  wvlet-api/src/main/scala/wvlet/lang/api/v1/frontend/FrontendApi.scala
  wvlet-api/src/main/scala/wvlet/lang/api/v1/query/QueryInfo.scala
  wvlet-api/src/main/scala/wvlet/lang/api/v1/query/QueryStatus.scala
  wvlet-server/src/main/scala/wvlet/lang/api/server/FrontendApiImpl.scala
  wvlet-server/src/main/scala/wvlet/lang/api/server/WvletServer.scala
  wvlet-server/src/main/scala/wvlet/lang/api/server/WvletServerMain.scala
  wvlet-server/src/test/scala/wvlet/lang/api/server/WvletServerMainTest.scala
  wvlet-server/src/test/scala/wvlet/lang/api/server/WvletServerTest.scala
Labels: feature

#306 editor (feature): Integrate UI with RPC server
  build.sbt
  wvlet-server/src/main/scala/wvlet/lang/api/server/FrontendApiImpl.scala
  wvlet-server/src/main/scala/wvlet/lang/api/server/WvletServerMain.scala
  wvlet-ui-main/README.md
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/WvletUIMain.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletEditor.scala
  wvlet-ui-main/vite.config.js
Labels: feature, doc

#307 editor (feature): Run query from Web UI
  wvlet-api/src/main/scala/wvlet/lang/api/v1/query/QueryInfo.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/cli/WvletScriptRunner.scala
  wvlet-server/src/main/scala/wvlet/lang/api/server/FrontendApiImpl.scala
  wvlet-server/src/main/scala/wvlet/lang/api/server/QueryService.scala
  wvlet-server/src/main/scala/wvlet/lang/api/server/WvletServer.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/QueryResultReader.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletMonacoEditor.scala
Labels: feature

#308 editor (feature): Support multiline comment and interpolation
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletMonacoEditor.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletMonarchLanguage.scala
Labels: feature

#309 editor (feature): Add keyword completion
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletMonacoEditor.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletMonarchLanguage.scala
Labels: feature

#310 editor (fix): Fix monaco rendering error
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletMonacoEditor.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletMonarchLanguage.scala
Labels: bug

#311 editor (feature): Fill the entire screen
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/QueryResultReader.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletEditor.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletMonacoEditor.scala
Labels: feature

#312 editor (feature): Continuously fetch QueryInfo and show logs to console window"
  wvlet-server/src/main/scala/wvlet/lang/api/server/FrontendApiImpl.scala
  wvlet-server/src/main/scala/wvlet/lang/api/server/QueryService.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/ConsoleLogWindow.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/QueryResultReader.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletEditor.scala
Labels: feature

#313 editor (feature): Show result preview
  wvlet-api/src/main/scala/wvlet/lang/api/v1/query/QueryInfo.scala
  wvlet-server/src/main/scala/wvlet/lang/api/server/QueryService.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/PreviewWindow.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/QueryResultReader.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletEditor.scala
  wvlet-ui/src/main/scala/wvlet/lang/ui/component/MainFrame.scala
Labels: feature

#314 editor (feature): Show query error message in the console
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/ConsoleLogWindow.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/QueryResultReader.scala
Labels: feature

#317 editor (feature): Use fixed editor layout
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/ConsoleLogWindow.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletEditor.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletMonacoEditor.scala
  wvlet-ui/src/main/scala/wvlet/lang/ui/component/MainFrame.scala
Labels: bug, feature

#318 editor (feature): Stabilize editor height
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletEditor.scala
  wvlet-ui/src/main/scala/wvlet/lang/ui/component/MainFrame.scala
Labels: feature

#319 editor (feature): Support test/describe with ctrl-j ctrl-t/ctrl-d shortcut keys
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletMonacoEditor.scala
Labels: feature

#320 internal: Move cli classes to depend on both runner and server
  build.sbt
  wvlet-cli/src/main/scala/wvlet/lang/cli/Clipboard.scala
  wvlet-cli/src/main/scala/wvlet/lang/cli/Profile.scala
  wvlet-cli/src/main/scala/wvlet/lang/cli/WvletCompilerCli.scala
  wvlet-cli/src/main/scala/wvlet/lang/cli/WvletREPL.scala
  wvlet-cli/src/test/scala/wvlet/lang/cli/WvletCliTest.scala
  wvlet-cli/src/test/scala/wvlet/lang/cli/WvletREPLTest.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/ProcessUtil.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/WvletScriptRunner.scala
  wvlet-server/src/main/scala/wvlet/lang/api/server/QueryService.scala
  wvlet-server/src/main/scala/wvlet/lang/api/server/WvletServer.scala
  wvlet-spec/src/test/scala/wvlet/lang/spec/TDTrinoSpec.scala
Labels: internal

#321 internal: Add cli project to root project
  build.sbt
Labels: internal

#322 internal: Split wv, wvc, wvlet commands
  build.sbt
  wvlet-cli/src/main/scala/wvlet/lang/cli/WvMain.scala
  wvlet-cli/src/main/scala/wvlet/lang/cli/WvcMain.scala
  wvlet-cli/src/main/scala/wvlet/lang/cli/WvletGlobalOption.scala
  wvlet-cli/src/main/scala/wvlet/lang/cli/WvletMain.scala
  wvlet-cli/src/main/scala/wvlet/lang/cli/WvletREPL.scala
  wvlet-cli/src/test/scala/wvlet/lang/cli/WvMainTest.scala
  wvlet-cli/src/test/scala/wvlet/lang/cli/WvcMainTest.scala
  wvlet-server/src/main/scala/wvlet/lang/api/server/QueryService.scala
  wvlet-spec/src/test/scala/wvlet/lang/spec/TDTrinoSpec.scala
Labels: internal

#324 editor (feature): Add 'wvlet ui' command to launch UI server
  build.sbt
  wvlet-cli/src/main/scala/wvlet/lang/cli/WvletMain.scala
  wvlet-server/src/main/scala/wvlet/lang/api/server/StaticContentApi.scala
  wvlet-server/src/main/scala/wvlet/lang/api/server/WvletServer.scala
Labels: feature

#325 editor (feature): editor (feature): Add -w option to wvlet ui
  .github/workflows/test.yml
  build.sbt
  wvlet-lang/src/main/scala/wvlet/lang/catalog/Profile.scala
  wvlet-server/src/main/scala/wvlet/lang/api/server/WvletServer.scala
  wvlet-server/src/main/scala/wvlet/lang/api/server/WvletServerMain.scala
  wvlet-server/src/main/scala/wvlet/lang/cli/Clipboard.scala
  wvlet-server/src/main/scala/wvlet/lang/cli/WvMain.scala
  wvlet-server/src/main/scala/wvlet/lang/cli/WvcMain.scala
  wvlet-server/src/main/scala/wvlet/lang/cli/WvletGlobalOption.scala
  wvlet-server/src/main/scala/wvlet/lang/cli/WvletMain.scala
  wvlet-server/src/main/scala/wvlet/lang/cli/WvletREPL.scala
  wvlet-server/src/test/scala/wvlet/lang/api/server/WvletServerMainTest.scala
  wvlet-server/src/test/scala/wvlet/lang/cli/WvMainTest.scala
  wvlet-server/src/test/scala/wvlet/lang/cli/WvcMainTest.scala
  wvlet-spec/src/test/scala/wvlet/lang/spec/TDTrinoSpec.scala
Labels: feature

#327 editor (internal): reorganize main classes
  wvlet-server/src/main/scala/wvlet/lang/api/server/WvletServer.scala
  wvlet-server/src/main/scala/wvlet/lang/cli/WvletMain.scala
  wvlet-server/src/main/scala/wvlet/lang/cli/WvletREPLMain.scala
  wvlet-server/src/test/scala/wvlet/lang/cli/WvletMainTest.scala
  wvlet-server/src/test/scala/wvlet/lang/cli/WvletREPLMainTest.scala
Labels: internal

#331 editor (feature): Open the ui page in the web browser upon start
  wvlet-server/src/main/scala/wvlet/lang/api/server/QueryService.scala
  wvlet-server/src/main/scala/wvlet/lang/api/server/WvletServer.scala
  wvlet-server/src/main/scala/wvlet/lang/cli/Clipboard.scala
  wvlet-server/src/main/scala/wvlet/lang/cli/OS.scala
Labels: feature

#333 editor (feature #265): Add clip-query command to REPL
  wvlet-server/src/main/scala/wvlet/lang/cli/WvletREPL.scala
  wvlet-server/src/test/scala/wvlet/lang/cli/WvletREPLMainTest.scala
Labels: feature

#335 editor (fix): Fix main class name for sbt-pack
  build.sbt
Labels: bug

#334 editor (feature #265): show query command
  spec/basic/show-query.wv
  wvlet-lang/src/main/scala/wvlet/lang/compiler/CompilationUnit.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/Symbolnfo.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/analyzer/SymbolLabeler.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/parser/WvletParser.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/parser/WvletToken.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/planner/ExecutionPlanner.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/commands.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/ddl.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/execution.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/relation.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/QueryExecutor.scala
  wvlet-server/src/main/scala/wvlet/lang/cli/WvletMain.scala
  wvlet-server/src/main/scala/wvlet/lang/cli/WvletREPLMain.scala
Labels: feature

#336 runner (feature #203): Skip tests in production runs
  build.sbt
  wvlet-api/src/main/scala/wvlet/lang/api/v1/frontend/FrontendApi.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/Context.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/planner/ExecutionPlanner.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/WvletScriptRunner.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/cli/Clipboard.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/cli/OS.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/cli/WvcMain.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/cli/WvletGlobalOption.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/cli/WvletREPL.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/cli/WvletREPLMain.scala
  wvlet-runner/src/test/scala/wvlet/lang/runner/SpecRunner.scala
  wvlet-runner/src/test/scala/wvlet/lang/runner/cli/WvcMainTest.scala
  wvlet-runner/src/test/scala/wvlet/lang/runner/cli/WvletREPLMainTest.scala
  wvlet-server/src/main/scala/wvlet/lang/server/FrontendApiImpl.scala
  wvlet-server/src/main/scala/wvlet/lang/server/QueryService.scala
  wvlet-server/src/main/scala/wvlet/lang/server/StaticContentApi.scala
  wvlet-server/src/main/scala/wvlet/lang/server/WvletServer.scala
  wvlet-server/src/main/scala/wvlet/lang/server/WvletServerMain.scala
  wvlet-server/src/test/scala/wvlet/lang/cli/WvletMainTest.scala
  wvlet-server/src/test/scala/wvlet/lang/server/WvletServerMainTest.scala
  wvlet-server/src/test/scala/wvlet/lang/server/WvletServerTest.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/QueryResultReader.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletMonacoEditor.scala
Labels: feature

#337 lang (feature): Add a handy method for reporting compilation errors
  wvlet-lang/src/main/scala/wvlet/lang/compiler/Compiler.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/cli/WvcMain.scala
Labels: feature

#338 runner (internal): Fix cli project structure and add ThreadManager for safe DuckDB shutdown
  build.sbt
  wvlet-cli/src/main/scala/wvlet/lang/cli/Clipboard.scala
  wvlet-cli/src/main/scala/wvlet/lang/cli/WvcMain.scala
  wvlet-cli/src/main/scala/wvlet/lang/cli/WvletGlobalOption.scala
  wvlet-cli/src/main/scala/wvlet/lang/cli/WvletMain.scala
  wvlet-cli/src/main/scala/wvlet/lang/cli/WvletREPL.scala
  wvlet-cli/src/main/scala/wvlet/lang/cli/WvletREPLMain.scala
  wvlet-cli/src/test/scala/wvlet/lang/cli/WvcMainTest.scala
  wvlet-cli/src/test/scala/wvlet/lang/cli/WvletMainTest.scala
  wvlet-cli/src/test/scala/wvlet/lang/cli/WvletREPLMainTest.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/OS.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/ThreadUtil.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/WvletScriptRunner.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/connector/ConnectorCatalog.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/connector/duckdb/DuckDBConnector.scala
  wvlet-server/src/main/scala/wvlet/lang/server/WvletServer.scala
  wvlet-server/src/main/scala/wvlet/lang/server/WvletServerMain.scala
  wvlet-server/src/test/scala/wvlet/lang/server/WvletServerMainTest.scala
Labels: bug, internal

#339 editor (internal): Supprress unnecessary log
  wvlet-server/src/main/scala/wvlet/lang/server/StaticContentApi.scala
Labels: internal

#341 editor (feature): Add FileApi to navigate local file contents
  wvlet-api/src/main/scala/wvlet/lang/api/v1/frontend/FileApi.scala
  wvlet-api/src/main/scala/wvlet/lang/api/v1/frontend/FrontendApi.scala
  wvlet-api/src/main/scala/wvlet/lang/api/v1/io/FileEntry.scala
  wvlet-server/src/main/scala/wvlet/lang/server/FileApiImpl.scala
  wvlet-server/src/main/scala/wvlet/lang/server/FrontendApiImpl.scala
  wvlet-server/src/main/scala/wvlet/lang/server/WvletServer.scala
  wvlet-server/src/test/scala/wvlet/lang/server/FileApiImplTest.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/FileNav.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletEditor.scala
Labels: feature

#342 editor (feature): Add file selector UI
  wvlet-server/src/main/scala/wvlet/lang/server/FileApiImpl.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/FileNav.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/QueryResultReader.scala
  wvlet-ui/src/main/scala/wvlet/lang/ui/component/Icon.scala
Labels: feature

#343 editor (feature #332): Load .wv file from path
  wvlet-api/src/main/scala/wvlet/lang/api/v1/io/FileEntry.scala
  wvlet-server/src/main/scala/wvlet/lang/server/FileApiImpl.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/WvletUIMain.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/FileNav.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/QueryResultReader.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletEditor.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletMonacoEditor.scala
  wvlet-ui/src/main/scala/wvlet/lang/ui/component/GlobalState.scala
  wvlet-ui/src/main/scala/wvlet/lang/ui/component/MainFrame.scala
  wvlet-ui/src/main/scala/wvlet/lang/ui/component/URLParamManager.scala
Labels: feature

#344 editor (feature): Manage relative paths in FileApi
  wvlet-server/src/main/scala/wvlet/lang/server/FileApiImpl.scala
  wvlet-server/src/main/scala/wvlet/lang/server/QueryService.scala
  wvlet-server/src/test/scala/wvlet/lang/server/FileApiImplTest.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/QueryResultReader.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletMonacoEditor.scala
  wvlet-ui/src/main/scala/wvlet/lang/ui/component/URLParamManager.scala
Labels: feature

#345 editor (feature): Run test with ctrl-enter in Web UI
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletMonacoEditor.scala
Labels: feature

#346 editor (feature): Add --profile, --catalog, --schema option to wvlet ui command
  wvlet-cli/src/main/scala/wvlet/lang/cli/WvletREPLMain.scala
  wvlet-lang/src/main/scala/wvlet/lang/catalog/Profile.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/connector/DBConnectorProvider.scala
  wvlet-server/src/main/scala/wvlet/lang/server/WvletServer.scala
Labels: feature

#347 editor (feature): Preload small TPC-H dataset for the ease of testing (--tpch option)
  build.sbt
  wvlet-lang/src/main/scala/wvlet/lang/catalog/Profile.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/connector/DBConnectorProvider.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/connector/duckdb/DuckDBConnector.scala
  wvlet-server/src/main/scala/wvlet/lang/server/WvletServer.scala
Labels: feature

#349 editor (feature): Enable loading TPCH with --tpch option
  wvlet-server/src/main/scala/wvlet/lang/server/WvletServer.scala
Labels: feature

#350 editor (fix): Properly iterate until query completion
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/QueryResultReader.scala
Labels: bug

#352 editor (feature: #332): Run queries with debug mode by default in REPL and WebUI
  spec/basic/shift.wv
  wvlet-api/src/main/scala/wvlet/lang/api/v1/frontend/FrontendApi.scala
  wvlet-cli/src/main/scala/wvlet/lang/cli/WvletREPL.scala
  wvlet-cli/src/test/scala/wvlet/lang/cli/WvletREPLMainTest.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/Context.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/planner/ExecutionPlanner.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/QueryExecutor.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/QueryResultPrinter.scala
  wvlet-server/src/main/scala/wvlet/lang/server/QueryService.scala
  wvlet-server/src/main/scala/wvlet/lang/server/WvletServer.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/QueryResultReader.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletMonacoEditor.scala
Labels: feature

#353 editor (feature): Add navbar links to doc and GitHub
  wvlet-ui/src/main/scala/wvlet/lang/ui/component/MainFrame.scala
Labels: feature

#354 editor (feature): Use different port if default port 9090 is unavailable
  build.sbt
  wvlet-server/src/main/scala/wvlet/lang/server/WvletServer.scala
Labels: feature

#355 editor (feature): Shortcut keys run (ctrl-enter), test (shift-enter), prod run (cmd-enter)
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletMonacoEditor.scala
Labels: feature

#357 editor (internal): Remove dumb terminal warning during sbt tests
  build.sbt
  wvlet-cli/src/main/scala/wvlet/lang/cli/WvletREPL.scala
Labels: internal

#358 lang (fix): Properly close DuckDB when wvc finishes
  wvlet-cli/src/main/scala/wvlet/lang/cli/WvcMain.scala
Labels: bug

#362 editor (feature): Report error location in the web editor
  wvlet-api/src/main/scala/wvlet/lang/api/SourceLocation.scala
  wvlet-api/src/main/scala/wvlet/lang/api/StatusCode.scala
  wvlet-api/src/main/scala/wvlet/lang/api/WvletLangException.scala
  wvlet-api/src/main/scala/wvlet/lang/api/v1/query/QueryInfo.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/SourceFile.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/QueryResult.scala
  wvlet-server/src/main/scala/wvlet/lang/server/QueryService.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/WvletUIMain.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/QueryResultReader.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletMonacoEditor.scala
Labels: feature

#363 editor (feature): make the default editor height smaller
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletEditor.scala
Labels: feature

#364 internal: Reorganize QueryRequest/QueryInfo for conveying further info
  wvlet-api/src/main/scala/wvlet/lang/api/v1/frontend/FrontendApi.scala
  wvlet-api/src/main/scala/wvlet/lang/api/v1/query/QueryInfo.scala
  wvlet-api/src/main/scala/wvlet/lang/api/v1/query/QueryRequest.scala
  wvlet-api/src/main/scala/wvlet/lang/api/v1/query/QuerySelection.scala
  wvlet-api/src/main/scala/wvlet/lang/api/v1/query/QueryStatus.scala
  wvlet-cli/src/main/scala/wvlet/lang/cli/WvletREPL.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/Context.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/WvletScriptRunner.scala
  wvlet-runner/src/test/scala/wvlet/lang/runner/SpecRunner.scala
  wvlet-server/src/main/scala/wvlet/lang/server/FrontendApiImpl.scala
  wvlet-server/src/main/scala/wvlet/lang/server/QueryService.scala
  wvlet-server/src/test/scala/wvlet/lang/server/WvletServerTest.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/WvletUIMain.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/QueryResultReader.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/WvletMonacoEditor.scala
Labels: internal

#365 editor (feature): Enable running only selected part of queries
  wvlet-api/src/main/scala/wvlet/lang/api/Span.scala
  wvlet-api/src/main/scala/wvlet/lang/api/v1/query/QueryRequest.scala
  wvlet-cli/src/main/scala/wvlet/lang/cli/WvletREPL.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/SourceFile.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/planner/ExecutionPlanner.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/relation.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/QueryExecutor.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/QuerySelector.scala
  wvlet-runner/src/main/scala/wvlet/lang/runner/WvletScriptRunner.scala
Labels: feature

#367 fix: Ensure using monospace font for rendering tables properly in Windows
  website/src/css/custom.css
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/PreviewWindow.scala
Labels: bug

#369 editor (fix #366): Use Consolas for fixed-width bars
  wvlet-ui-main/tailwind.config.js
Labels: bug

#370 editor (fix #366): Hide horizontal scrollbar for Edge on Windows
  wvlet-ui-main/index.css
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/ConsoleLogWindow.scala
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/PreviewWindow.scala
Labels: bug

#371 doc: Update installation note for Windows
  website/docs/development/build.md
  website/docs/usage/install.md
Labels: doc

#375 editor (fix): Fix to use given catalog and schema in profile
  wvlet-server/src/main/scala/wvlet/lang/server/WvletServer.scala
Labels: bug

#376 editor (feature): Add a new file/directory button
  wvlet-ui-main/src/main/scala/wvlet/lang/ui/editor/FileNav.scala
Labels: feature
