Repository wvlet/wvlet, pull requests merged in 2025-08, with the labels that each got.

#1059 feature: Added command to convert query language
  wvlet-cli/src/main/scala/wvlet/lang/cli/WvletCompiler.scala
  wvlet-cli/src/main/scala/wvlet/lang/cli/WvletMain.scala
  wvlet-cli/src/test/scala/wvlet/lang/cli/QueryConverterCommandTest.scala
  wvlet-cli/src/test/scala/wvlet/lang/cli/WvletREPLMainTest.scala
Labels: feature

#1078 fix: Support IF function as SQL expression instead of keyword
  spec/sql/basic/if-function.sql
  wvlet-lang/src/main/scala/wvlet/lang/compiler/parser/SqlToken.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/transform/RewriteExpr.scala
  wvlet-lang/src/test/scala/wvlet/lang/compiler/codegen/WvletGeneratorTest.scala
Labels: bug, feature

#1080 fix: Allow reserved keywords as unquoted identifiers in SQL
  spec/sql/basic/reserved-keywords.sql
  website/docs/development/sql-grammar.md
  wvlet-lang/src/main/scala/wvlet/lang/compiler/parser/SqlParser.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/parser/SqlToken.scala
Labels: bug, doc

#1082 fix: Support dot notation for schema.table and reserved keywords as identifiers
  spec/sql/basic/create-schema.sql
  spec/sql/basic/reserved-keywords.sql
  spec/sql/basic/schema-dot-table.sql
  wvlet-lang/src/main/scala/wvlet/lang/catalog/Catalog.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/Name.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/codegen/LogicalPlanPrinter.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/codegen/SqlGenerator.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/codegen/WvletGenerator.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/parser/SqlParser.scala
  wvlet-lang/src/main/scala/wvlet/lang/compiler/parser/SqlToken.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/expr/exprs.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/ddl.scala
  wvlet-lang/src/main/scala/wvlet/lang/model/plan/relation.scala
  wvlet-lang/src/test/scala/wvlet/lang/catalog/TableNameTest.scala
  wvlet-lang/src/test/scala/wvlet/lang/compiler/codegen/InsertIntoCodegenTest.scala
Labels: bug, feature

#1106 Add Claude Code GitHub Workflow
  .github/workflows/claude-code-review.yml.template
  .github/workflows/claude.yml
Labels: internal

#1111 feature: Add highlight.js extension for Wvlet language syntax highlighting
  .github/workflows/highlightjs.yml
  .github/workflows/test.yml
  highlightjs-wvlet/.gitignore
  highlightjs-wvlet/LICENSE
  highlightjs-wvlet/README.md
  highlightjs-wvlet/build.js
  highlightjs-wvlet/dist/wvlet.js
  highlightjs-wvlet/dist/wvlet.min.js
  highlightjs-wvlet/package-lock.json
  highlightjs-wvlet/package.json
  highlightjs-wvlet/src/languages/wvlet.js
  highlightjs-wvlet/test.html
  highlightjs-wvlet/test/detect/wvlet/default.txt
  highlightjs-wvlet/test/index.js
  highlightjs-wvlet/test/markup/index.js
  highlightjs-wvlet/test/markup/wvlet/basic.expect.txt
  highlightjs-wvlet/test/markup/wvlet/basic.txt
Labels: feature, doc

#1112 feature: Add NPM publishing for highlight.js Wvlet extension
  .github/workflows/highlightjs.yml
  .github/workflows/npm-publish.yml
  .github/workflows/typescript-npm-publish.yml
Labels: feature

#1113 feature: Add Dependabot configuration for highlight.js extension
  .github/dependabot.yml
  .github/workflows/highlightjs.yml
Labels: feature

#1116 feature: Add path-filter action to highlight.js CI workflow
  .github/workflows/highlightjs.yml
Labels: feature

#1117 fix: Set working-directory for Scala.js build in npm-publish workflow
  .github/workflows/npm-publish.yml
Labels: bug

#1118 doc: Add CDN test page for highlight.js Wvlet extension
  highlightjs-wvlet/README.md
  highlightjs-wvlet/test-cdn.html
Labels: doc

#1120 fix: Add 'wvlet' alias and auto-registration for browser usage
  highlightjs-wvlet/README.md
  highlightjs-wvlet/build.js
  highlightjs-wvlet/dist/wvlet.js
  highlightjs-wvlet/dist/wvlet.min.js
  highlightjs-wvlet/src/languages/wvlet.js
  highlightjs-wvlet/test-cdn.html
  highlightjs-wvlet/test.html
Labels: bug, doc

#1123 feature: Add Prism.js syntax highlighting support for Wvlet
  .github/dependabot.yml
  .github/workflows/npm-publish.yml
  .github/workflows/prismjs.yml
  highlightjs-wvlet/package-lock.json
  prismjs-wvlet/.gitignore
  prismjs-wvlet/README.md
  prismjs-wvlet/build.js
  prismjs-wvlet/components/prism-wvlet.js
  prismjs-wvlet/examples/cdn-test.html
  prismjs-wvlet/examples/index.html
  prismjs-wvlet/jest.config.js
  prismjs-wvlet/package-lock.json
  prismjs-wvlet/package.json
  prismjs-wvlet/test/fixtures/basic.wv
  prismjs-wvlet/test/prism-wvlet.test.js
Labels: feature, doc

#1127 feature: Add Wvlet syntax highlighting support to Docusaurus
  website/docs/development/design.md
  website/docs/index.md
  website/docs/syntax/asof-join.md
  website/docs/syntax/data-models.md
  website/docs/syntax/index.md
  website/docs/syntax/quick-start.md
  website/docs/syntax/test-syntax.md
  website/docs/syntax/unnest.md
  website/docs/syntax/window.md
  website/docs/usage/cli.md
  website/package-lock.json
  website/package.json
  website/src/theme/prism-include-languages.ts
Labels: feature, doc

#1128 docs: Add comprehensive syntax highlighting documentation
  highlightjs-wvlet/README.md
  prismjs-wvlet/README.md
  website/docs/development/syntax-highlighting.md
Labels: doc
